version: "3"
services:
# SQLのサービス
  db:
    image: mysql:8
    container_name: "spring_db"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/sql/:/docker-entrypoint-initdb.d
      - ./mysql/settings/:/var/lib/mysql
      - ./mysql/sql/mysql.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: "sample" # この場合sampleというデータベースが作成されます
      MYSQL_ROOT_USER: "root" # rootユーザーはパスワードを設定しないとエラーでます
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Asia/Tokyo"

  # springアプリケーションのサービス
  spring-api-test:
    image: openjdk:11
    container_name: "spring-api-test"
    restart: always
    ports:
      - "9090:8080"
    tty: true
    depends_on:
      - db
    volumes:
      - ./spring-api-test:/spring-api-test
    working_dir: /spring-api-test
